# Generated by Django 4.0.6 on 2022-07-14 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='wishlist',
            new_name='watchlist',
        ),
    ]
