# Generated by Django 4.0.6 on 2022-07-14 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rename_wishlist_movie_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='watchlist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='movies.watchlist'),
        ),
    ]
